### ISSUE TITLE
a simple question ,expect your early reply,thanks a lot

### ISSUE THREAD

**Issue by xoyabc** [danfromisrael/TodoApp-Flask-Angular#4]
I wonder how the file "config.py" works,I have read your code for a long time and cannot find where does it use.
Would you please tell me where and how it works?

**Comment by buzzdan** [comment]
Hi 😊
It been a while since i touched this code, 
It seems that its not in use but was copied from the tutorial:
https://realpython.com/blog/python/flask-by-example-part-1-project-setup/

The original line that loads it in ruserver.py is commented out...

**Comment by xoyabc** [comment]
@buzzdan   Thank you

**Comment by buzzdan** [comment]
you welcome ;)
